# Generated by Django 5.2.6 on 2025-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('student_class', models.CharField(max_length=15)),
                ('student_roll_no', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
